version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Mostrar estructura de archivos
          command: |
            echo "Mostrando estructura del proyecto..."
            ls -R

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Simular despliegue
          command: echo "Simulación de despliegue exitoso para HTML estático."

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

