version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install
      - run:
          name: Compilar proyecto
          command: npm run build

  deploy:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Desplegar a Vercel
          command: |
            npm install -g vercel
            vercel --prod --token=$VERCEL_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
