name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test on develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify HTML files exist
        run: |
          echo "Verificando que haya archivos HTML en html/..."
          # Intenta listar html/*.html; si no hay nada, falla
          if [ -z "$(ls html/*.html 2>/dev/null)" ]; then
            echo "❌ No se encontraron archivos .html en html/"
            exit 1
          else
            echo "✅ Archivos HTML detectados:"
            ls html/*.html
          fi

      - name: (Opcional) Lint HTML
        run: |
          echo "Instalando htmlhint..."
          npm install -g htmlhint
          echo "Revisando html/*.html:"
          htmlhint "html/*.html"

  deploy:
    name: Deploy on merge to main
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html            # <- publicamos el contenido de html/
